id: A19564547
title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
  ‘The Heart Essence of the Sublime Lady of Immortality’
type: translation
pechas:
- I76620442
- I8C62925E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:57.247720
  last_modified_at: 2023-01-04 12:36:57.247728
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I76620442/E43A: '4759'
  I8C62925E/5AB2: '4759'
